# This is a basic workflow to help you get started with Actions

name: Generate static files and Deploy to Scaleway Object Storage

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Node version we want to run
    strategy:
      matrix:
        node-version: [18.x]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Checkout the code
      uses: actions/checkout@v2
      with:
        submodules: 'recursive'

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
      
    - name: Install dependencies
      run: npm install

    - name: Production Generation
      run: |
        npm run generate
      
    - name: Configure Scaleway credentials
      uses: scaleway/github-action@v1
      with:
        access-key: ${{ secrets.SCW_ACCESS_KEY_ID }}
        secret-key: ${{ secrets.SCW_SECRET_ACCESS_KEY }}
        region: 'fr-par'
        
    - name: Deploy to Scaleway Object Storage
      uses: scaleway/github-action@v1
      with:
        command: 'scw --region=fr-par object put --acl=public-read --mime-type=text/html ./dist/* s3://blog-dps'